export const TitlePlaceholder = 'Movie title'
export const MovieUrlPlaceholder = 'https://'
export const ReleaseDatePlaceholder = 'Select Date'
export const GenrePlaceholder = 'Select Genre'
export const RatingPlaceholder = '7.8'
export const RuntimePlaceholder = 'minutes'
export const OverviewPlaceholder = 'Movie description'
